version: "3"
services:
  minio1:
    image: minio/minio
    command: server http://minio{1...2}/data{1...4}
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=minio123"
    ports:
      - "9000:9000"
    volumes:
    - ./data1-1:/data1
    - ./data1-2:/data2
    - ./data1-3:/data3
    - ./data1-4:/data4
  minio2:
    image: minio/minio
    command: server http://minio{1...2}/data{1...4}
    environment:
        - "MINIO_ROOT_USER=minio"
        - "MINIO_ROOT_PASSWORD=minio123"
    ports:
      - "9001:9000"
    volumes:
    - ./data2-1:/data1
    - ./data2-2:/data2
    - ./data2-3:/data3
    - ./data2-4:/data4
  sidekick:
    image: minio/sidekick
    command: --debug --health-path=/minio/health/ready --address :8000 http://minio{1...2}:9000
    ports: 
    - "8000:8000"
  console:
    image: minio/console
    command: server
    environment:
      - "CONSOLE_PBKDF_PASSPHRASE=demoapp"
      - "CONSOLE_PBKDF_SALT=demoapp"
      - "CONSOLE_MINIO_SERVER=http://minio1:9000"
    ports:
      - "9090:9090"
